name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.6.2
  - seaborn=0.12.2
  - pandas=1.5.3
  - pip=20.3.3
  - ydata-profiling=4.1.1
  - pyarrow=11.0
  - pip:
      - wandb==0.15.0